# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = /usr/bin/ccmake

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/local1/workspace/MINOS_simulation

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/local1/workspace/MINOS_simulation

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/local1/workspace/MINOS_simulation/CMakeFiles /home/local1/workspace/MINOS_simulation/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/local1/workspace/MINOS_simulation/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named MINOS_sim

# Build rule for target.
MINOS_sim: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 MINOS_sim
.PHONY : MINOS_sim

# fast build rule for target.
MINOS_sim/fast:
	$(MAKE) -f CMakeFiles/MINOS_sim.dir/build.make CMakeFiles/MINOS_sim.dir/build
.PHONY : MINOS_sim/fast

MINOS_sim.o: MINOS_sim.cc.o
.PHONY : MINOS_sim.o

# target to build an object file
MINOS_sim.cc.o:
	$(MAKE) -f CMakeFiles/MINOS_sim.dir/build.make CMakeFiles/MINOS_sim.dir/MINOS_sim.cc.o
.PHONY : MINOS_sim.cc.o

MINOS_sim.i: MINOS_sim.cc.i
.PHONY : MINOS_sim.i

# target to preprocess a source file
MINOS_sim.cc.i:
	$(MAKE) -f CMakeFiles/MINOS_sim.dir/build.make CMakeFiles/MINOS_sim.dir/MINOS_sim.cc.i
.PHONY : MINOS_sim.cc.i

MINOS_sim.s: MINOS_sim.cc.s
.PHONY : MINOS_sim.s

# target to generate assembly for a file
MINOS_sim.cc.s:
	$(MAKE) -f CMakeFiles/MINOS_sim.dir/build.make CMakeFiles/MINOS_sim.dir/MINOS_sim.cc.s
.PHONY : MINOS_sim.cc.s

src/ExN03DetectorConstruction.o: src/ExN03DetectorConstruction.cc.o
.PHONY : src/ExN03DetectorConstruction.o

# target to build an object file
src/ExN03DetectorConstruction.cc.o:
	$(MAKE) -f CMakeFiles/MINOS_sim.dir/build.make CMakeFiles/MINOS_sim.dir/src/ExN03DetectorConstruction.cc.o
.PHONY : src/ExN03DetectorConstruction.cc.o

src/ExN03DetectorConstruction.i: src/ExN03DetectorConstruction.cc.i
.PHONY : src/ExN03DetectorConstruction.i

# target to preprocess a source file
src/ExN03DetectorConstruction.cc.i:
	$(MAKE) -f CMakeFiles/MINOS_sim.dir/build.make CMakeFiles/MINOS_sim.dir/src/ExN03DetectorConstruction.cc.i
.PHONY : src/ExN03DetectorConstruction.cc.i

src/ExN03DetectorConstruction.s: src/ExN03DetectorConstruction.cc.s
.PHONY : src/ExN03DetectorConstruction.s

# target to generate assembly for a file
src/ExN03DetectorConstruction.cc.s:
	$(MAKE) -f CMakeFiles/MINOS_sim.dir/build.make CMakeFiles/MINOS_sim.dir/src/ExN03DetectorConstruction.cc.s
.PHONY : src/ExN03DetectorConstruction.cc.s

src/ExN03EventAction.o: src/ExN03EventAction.cc.o
.PHONY : src/ExN03EventAction.o

# target to build an object file
src/ExN03EventAction.cc.o:
	$(MAKE) -f CMakeFiles/MINOS_sim.dir/build.make CMakeFiles/MINOS_sim.dir/src/ExN03EventAction.cc.o
.PHONY : src/ExN03EventAction.cc.o

src/ExN03EventAction.i: src/ExN03EventAction.cc.i
.PHONY : src/ExN03EventAction.i

# target to preprocess a source file
src/ExN03EventAction.cc.i:
	$(MAKE) -f CMakeFiles/MINOS_sim.dir/build.make CMakeFiles/MINOS_sim.dir/src/ExN03EventAction.cc.i
.PHONY : src/ExN03EventAction.cc.i

src/ExN03EventAction.s: src/ExN03EventAction.cc.s
.PHONY : src/ExN03EventAction.s

# target to generate assembly for a file
src/ExN03EventAction.cc.s:
	$(MAKE) -f CMakeFiles/MINOS_sim.dir/build.make CMakeFiles/MINOS_sim.dir/src/ExN03EventAction.cc.s
.PHONY : src/ExN03EventAction.cc.s

src/ExN03PhysicsList.o: src/ExN03PhysicsList.cc.o
.PHONY : src/ExN03PhysicsList.o

# target to build an object file
src/ExN03PhysicsList.cc.o:
	$(MAKE) -f CMakeFiles/MINOS_sim.dir/build.make CMakeFiles/MINOS_sim.dir/src/ExN03PhysicsList.cc.o
.PHONY : src/ExN03PhysicsList.cc.o

src/ExN03PhysicsList.i: src/ExN03PhysicsList.cc.i
.PHONY : src/ExN03PhysicsList.i

# target to preprocess a source file
src/ExN03PhysicsList.cc.i:
	$(MAKE) -f CMakeFiles/MINOS_sim.dir/build.make CMakeFiles/MINOS_sim.dir/src/ExN03PhysicsList.cc.i
.PHONY : src/ExN03PhysicsList.cc.i

src/ExN03PhysicsList.s: src/ExN03PhysicsList.cc.s
.PHONY : src/ExN03PhysicsList.s

# target to generate assembly for a file
src/ExN03PhysicsList.cc.s:
	$(MAKE) -f CMakeFiles/MINOS_sim.dir/build.make CMakeFiles/MINOS_sim.dir/src/ExN03PhysicsList.cc.s
.PHONY : src/ExN03PhysicsList.cc.s

src/ExN03PrimaryGeneratorAction.o: src/ExN03PrimaryGeneratorAction.cc.o
.PHONY : src/ExN03PrimaryGeneratorAction.o

# target to build an object file
src/ExN03PrimaryGeneratorAction.cc.o:
	$(MAKE) -f CMakeFiles/MINOS_sim.dir/build.make CMakeFiles/MINOS_sim.dir/src/ExN03PrimaryGeneratorAction.cc.o
.PHONY : src/ExN03PrimaryGeneratorAction.cc.o

src/ExN03PrimaryGeneratorAction.i: src/ExN03PrimaryGeneratorAction.cc.i
.PHONY : src/ExN03PrimaryGeneratorAction.i

# target to preprocess a source file
src/ExN03PrimaryGeneratorAction.cc.i:
	$(MAKE) -f CMakeFiles/MINOS_sim.dir/build.make CMakeFiles/MINOS_sim.dir/src/ExN03PrimaryGeneratorAction.cc.i
.PHONY : src/ExN03PrimaryGeneratorAction.cc.i

src/ExN03PrimaryGeneratorAction.s: src/ExN03PrimaryGeneratorAction.cc.s
.PHONY : src/ExN03PrimaryGeneratorAction.s

# target to generate assembly for a file
src/ExN03PrimaryGeneratorAction.cc.s:
	$(MAKE) -f CMakeFiles/MINOS_sim.dir/build.make CMakeFiles/MINOS_sim.dir/src/ExN03PrimaryGeneratorAction.cc.s
.PHONY : src/ExN03PrimaryGeneratorAction.cc.s

src/ExN03ROOTuple.o: src/ExN03ROOTuple.cc.o
.PHONY : src/ExN03ROOTuple.o

# target to build an object file
src/ExN03ROOTuple.cc.o:
	$(MAKE) -f CMakeFiles/MINOS_sim.dir/build.make CMakeFiles/MINOS_sim.dir/src/ExN03ROOTuple.cc.o
.PHONY : src/ExN03ROOTuple.cc.o

src/ExN03ROOTuple.i: src/ExN03ROOTuple.cc.i
.PHONY : src/ExN03ROOTuple.i

# target to preprocess a source file
src/ExN03ROOTuple.cc.i:
	$(MAKE) -f CMakeFiles/MINOS_sim.dir/build.make CMakeFiles/MINOS_sim.dir/src/ExN03ROOTuple.cc.i
.PHONY : src/ExN03ROOTuple.cc.i

src/ExN03ROOTuple.s: src/ExN03ROOTuple.cc.s
.PHONY : src/ExN03ROOTuple.s

# target to generate assembly for a file
src/ExN03ROOTuple.cc.s:
	$(MAKE) -f CMakeFiles/MINOS_sim.dir/build.make CMakeFiles/MINOS_sim.dir/src/ExN03ROOTuple.cc.s
.PHONY : src/ExN03ROOTuple.cc.s

src/ExN03RunAction.o: src/ExN03RunAction.cc.o
.PHONY : src/ExN03RunAction.o

# target to build an object file
src/ExN03RunAction.cc.o:
	$(MAKE) -f CMakeFiles/MINOS_sim.dir/build.make CMakeFiles/MINOS_sim.dir/src/ExN03RunAction.cc.o
.PHONY : src/ExN03RunAction.cc.o

src/ExN03RunAction.i: src/ExN03RunAction.cc.i
.PHONY : src/ExN03RunAction.i

# target to preprocess a source file
src/ExN03RunAction.cc.i:
	$(MAKE) -f CMakeFiles/MINOS_sim.dir/build.make CMakeFiles/MINOS_sim.dir/src/ExN03RunAction.cc.i
.PHONY : src/ExN03RunAction.cc.i

src/ExN03RunAction.s: src/ExN03RunAction.cc.s
.PHONY : src/ExN03RunAction.s

# target to generate assembly for a file
src/ExN03RunAction.cc.s:
	$(MAKE) -f CMakeFiles/MINOS_sim.dir/build.make CMakeFiles/MINOS_sim.dir/src/ExN03RunAction.cc.s
.PHONY : src/ExN03RunAction.cc.s

src/ExN03SteppingAction.o: src/ExN03SteppingAction.cc.o
.PHONY : src/ExN03SteppingAction.o

# target to build an object file
src/ExN03SteppingAction.cc.o:
	$(MAKE) -f CMakeFiles/MINOS_sim.dir/build.make CMakeFiles/MINOS_sim.dir/src/ExN03SteppingAction.cc.o
.PHONY : src/ExN03SteppingAction.cc.o

src/ExN03SteppingAction.i: src/ExN03SteppingAction.cc.i
.PHONY : src/ExN03SteppingAction.i

# target to preprocess a source file
src/ExN03SteppingAction.cc.i:
	$(MAKE) -f CMakeFiles/MINOS_sim.dir/build.make CMakeFiles/MINOS_sim.dir/src/ExN03SteppingAction.cc.i
.PHONY : src/ExN03SteppingAction.cc.i

src/ExN03SteppingAction.s: src/ExN03SteppingAction.cc.s
.PHONY : src/ExN03SteppingAction.s

# target to generate assembly for a file
src/ExN03SteppingAction.cc.s:
	$(MAKE) -f CMakeFiles/MINOS_sim.dir/build.make CMakeFiles/MINOS_sim.dir/src/ExN03SteppingAction.cc.s
.PHONY : src/ExN03SteppingAction.cc.s

src/ExN03TrackingAction.o: src/ExN03TrackingAction.cc.o
.PHONY : src/ExN03TrackingAction.o

# target to build an object file
src/ExN03TrackingAction.cc.o:
	$(MAKE) -f CMakeFiles/MINOS_sim.dir/build.make CMakeFiles/MINOS_sim.dir/src/ExN03TrackingAction.cc.o
.PHONY : src/ExN03TrackingAction.cc.o

src/ExN03TrackingAction.i: src/ExN03TrackingAction.cc.i
.PHONY : src/ExN03TrackingAction.i

# target to preprocess a source file
src/ExN03TrackingAction.cc.i:
	$(MAKE) -f CMakeFiles/MINOS_sim.dir/build.make CMakeFiles/MINOS_sim.dir/src/ExN03TrackingAction.cc.i
.PHONY : src/ExN03TrackingAction.cc.i

src/ExN03TrackingAction.s: src/ExN03TrackingAction.cc.s
.PHONY : src/ExN03TrackingAction.s

# target to generate assembly for a file
src/ExN03TrackingAction.cc.s:
	$(MAKE) -f CMakeFiles/MINOS_sim.dir/build.make CMakeFiles/MINOS_sim.dir/src/ExN03TrackingAction.cc.s
.PHONY : src/ExN03TrackingAction.cc.s

src/MinosModularList.o: src/MinosModularList.cc.o
.PHONY : src/MinosModularList.o

# target to build an object file
src/MinosModularList.cc.o:
	$(MAKE) -f CMakeFiles/MINOS_sim.dir/build.make CMakeFiles/MINOS_sim.dir/src/MinosModularList.cc.o
.PHONY : src/MinosModularList.cc.o

src/MinosModularList.i: src/MinosModularList.cc.i
.PHONY : src/MinosModularList.i

# target to preprocess a source file
src/MinosModularList.cc.i:
	$(MAKE) -f CMakeFiles/MINOS_sim.dir/build.make CMakeFiles/MINOS_sim.dir/src/MinosModularList.cc.i
.PHONY : src/MinosModularList.cc.i

src/MinosModularList.s: src/MinosModularList.cc.s
.PHONY : src/MinosModularList.s

# target to generate assembly for a file
src/MinosModularList.cc.s:
	$(MAKE) -f CMakeFiles/MINOS_sim.dir/build.make CMakeFiles/MINOS_sim.dir/src/MinosModularList.cc.s
.PHONY : src/MinosModularList.cc.s

src/MyMagneticField.o: src/MyMagneticField.cc.o
.PHONY : src/MyMagneticField.o

# target to build an object file
src/MyMagneticField.cc.o:
	$(MAKE) -f CMakeFiles/MINOS_sim.dir/build.make CMakeFiles/MINOS_sim.dir/src/MyMagneticField.cc.o
.PHONY : src/MyMagneticField.cc.o

src/MyMagneticField.i: src/MyMagneticField.cc.i
.PHONY : src/MyMagneticField.i

# target to preprocess a source file
src/MyMagneticField.cc.i:
	$(MAKE) -f CMakeFiles/MINOS_sim.dir/build.make CMakeFiles/MINOS_sim.dir/src/MyMagneticField.cc.i
.PHONY : src/MyMagneticField.cc.i

src/MyMagneticField.s: src/MyMagneticField.cc.s
.PHONY : src/MyMagneticField.s

# target to generate assembly for a file
src/MyMagneticField.cc.s:
	$(MAKE) -f CMakeFiles/MINOS_sim.dir/build.make CMakeFiles/MINOS_sim.dir/src/MyMagneticField.cc.s
.PHONY : src/MyMagneticField.cc.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... MINOS_sim"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... MINOS_sim.o"
	@echo "... MINOS_sim.i"
	@echo "... MINOS_sim.s"
	@echo "... src/ExN03DetectorConstruction.o"
	@echo "... src/ExN03DetectorConstruction.i"
	@echo "... src/ExN03DetectorConstruction.s"
	@echo "... src/ExN03EventAction.o"
	@echo "... src/ExN03EventAction.i"
	@echo "... src/ExN03EventAction.s"
	@echo "... src/ExN03PhysicsList.o"
	@echo "... src/ExN03PhysicsList.i"
	@echo "... src/ExN03PhysicsList.s"
	@echo "... src/ExN03PrimaryGeneratorAction.o"
	@echo "... src/ExN03PrimaryGeneratorAction.i"
	@echo "... src/ExN03PrimaryGeneratorAction.s"
	@echo "... src/ExN03ROOTuple.o"
	@echo "... src/ExN03ROOTuple.i"
	@echo "... src/ExN03ROOTuple.s"
	@echo "... src/ExN03RunAction.o"
	@echo "... src/ExN03RunAction.i"
	@echo "... src/ExN03RunAction.s"
	@echo "... src/ExN03SteppingAction.o"
	@echo "... src/ExN03SteppingAction.i"
	@echo "... src/ExN03SteppingAction.s"
	@echo "... src/ExN03TrackingAction.o"
	@echo "... src/ExN03TrackingAction.i"
	@echo "... src/ExN03TrackingAction.s"
	@echo "... src/MinosModularList.o"
	@echo "... src/MinosModularList.i"
	@echo "... src/MinosModularList.s"
	@echo "... src/MyMagneticField.o"
	@echo "... src/MyMagneticField.i"
	@echo "... src/MyMagneticField.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

