/********************************************************************
* .libsimclem_dict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error .libsimclem_dict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtabledOlibsimclem_dict();
extern void G__cpp_setup_inheritancedOlibsimclem_dict();
extern void G__cpp_setup_typetabledOlibsimclem_dict();
extern void G__cpp_setup_memvardOlibsimclem_dict();
extern void G__cpp_setup_globaldOlibsimclem_dict();
extern void G__cpp_setup_memfuncdOlibsimclem_dict();
extern void G__cpp_setup_funcdOlibsimclem_dict();
extern void G__set_cpp_environmentdOlibsimclem_dict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "TMinosTPCSimData.h"
#include "TMinosTrack.h"
#include "TMinosHough.h"
#include "TMinosClust.h"
#include "TMinosResult.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__dOlibsimclem_dictLN_TClass;
extern G__linked_taginfo G__dOlibsimclem_dictLN_TBuffer;
extern G__linked_taginfo G__dOlibsimclem_dictLN_TMemberInspector;
extern G__linked_taginfo G__dOlibsimclem_dictLN_TObject;
extern G__linked_taginfo G__dOlibsimclem_dictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__dOlibsimclem_dictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__dOlibsimclem_dictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__dOlibsimclem_dictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__dOlibsimclem_dictLN_TMinosTPCSimData;
extern G__linked_taginfo G__dOlibsimclem_dictLN_TMinosTrack;
extern G__linked_taginfo G__dOlibsimclem_dictLN_TMinosHough;
extern G__linked_taginfo G__dOlibsimclem_dictLN_TMinosClust;
extern G__linked_taginfo G__dOlibsimclem_dictLN_TMinosResult;

/* STUB derived class for protected member access */
