/********************************************************************
* ExN03DataiDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error ExN03DataiDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableExN03DataiDict();
extern void G__cpp_setup_inheritanceExN03DataiDict();
extern void G__cpp_setup_typetableExN03DataiDict();
extern void G__cpp_setup_memvarExN03DataiDict();
extern void G__cpp_setup_globalExN03DataiDict();
extern void G__cpp_setup_memfuncExN03DataiDict();
extern void G__cpp_setup_funcExN03DataiDict();
extern void G__set_cpp_environmentExN03DataiDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "ExN03Datai.hh"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__ExN03DataiDictLN_TClass;
extern G__linked_taginfo G__ExN03DataiDictLN_TBuffer;
extern G__linked_taginfo G__ExN03DataiDictLN_TMemberInspector;
extern G__linked_taginfo G__ExN03DataiDictLN_TObject;
extern G__linked_taginfo G__ExN03DataiDictLN_vectorlEdoublecOallocatorlEdoublegRsPgR;
extern G__linked_taginfo G__ExN03DataiDictLN_vectorlEboolcOallocatorlEboolgRsPgR;
extern G__linked_taginfo G__ExN03DataiDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__ExN03DataiDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__ExN03DataiDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__ExN03DataiDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__ExN03DataiDictLN_ExN03Datai;
extern G__linked_taginfo G__ExN03DataiDictLN_vectorlEintcOallocatorlEintgRsPgR;
extern G__linked_taginfo G__ExN03DataiDictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR;

/* STUB derived class for protected member access */
