/********************************************************************
* ExN03DataoDictRings.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error ExN03DataoDictRings.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableExN03DataoDictRings();
extern void G__cpp_setup_inheritanceExN03DataoDictRings();
extern void G__cpp_setup_typetableExN03DataoDictRings();
extern void G__cpp_setup_memvarExN03DataoDictRings();
extern void G__cpp_setup_globalExN03DataoDictRings();
extern void G__cpp_setup_memfuncExN03DataoDictRings();
extern void G__cpp_setup_funcExN03DataoDictRings();
extern void G__set_cpp_environmentExN03DataoDictRings();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "ExN03DataoRings.hh"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__ExN03DataoDictRingsLN_TClass;
extern G__linked_taginfo G__ExN03DataoDictRingsLN_TBuffer;
extern G__linked_taginfo G__ExN03DataoDictRingsLN_TMemberInspector;
extern G__linked_taginfo G__ExN03DataoDictRingsLN_TObject;
extern G__linked_taginfo G__ExN03DataoDictRingsLN_vectorlEdoublecOallocatorlEdoublegRsPgR;
extern G__linked_taginfo G__ExN03DataoDictRingsLN_string;
extern G__linked_taginfo G__ExN03DataoDictRingsLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__ExN03DataoDictRingsLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__ExN03DataoDictRingsLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__ExN03DataoDictRingsLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__ExN03DataoDictRingsLN_ExN03Datai;
extern G__linked_taginfo G__ExN03DataoDictRingsLN_vectorlEintcOallocatorlEintgRsPgR;
extern G__linked_taginfo G__ExN03DataoDictRingsLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__ExN03DataoDictRingsLN_ExN03DataoRings;

/* STUB derived class for protected member access */
