//
// File generated by rootcint at Thu Sep 10 15:31:32 2015

// Do NOT change. Changes will be lost next time file is generated
//

#define R__DICTIONARY_FILENAME ExN03BeamInDict
#include "RConfig.h" //rootcint 4834
#if !defined(R__ACCESS_IN_SYMBOL)
//Break the privacy of classes -- Disabled for the moment
#define private public
#define protected public
#endif

// Since CINT ignores the std namespace, we need to do so in this file.
namespace std {} using namespace std;
#include "ExN03BeamInDict.h"

#include "TClass.h"
#include "TBuffer.h"
#include "TMemberInspector.h"
#include "TInterpreter.h"
#include "TVirtualMutex.h"
#include "TError.h"

#ifndef G__ROOT
#define G__ROOT
#endif

#include "RtypesImp.h"
#include "TIsAProxy.h"
#include "TFileMergeInfo.h"

// Direct notice to TROOT of the dictionary's loading.
namespace {
   static struct DictInit {
      DictInit() {
         ROOT::RegisterModule();
      }
   } __TheDictionaryInitializer;
}

// START OF SHADOWS

namespace ROOT {
   namespace Shadow {
   } // of namespace Shadow
} // of namespace ROOT
// END OF SHADOWS

namespace ROOT {
   void ExN03BeamIn_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void *new_ExN03BeamIn(void *p = 0);
   static void *newArray_ExN03BeamIn(Long_t size, void *p);
   static void delete_ExN03BeamIn(void *p);
   static void deleteArray_ExN03BeamIn(void *p);
   static void destruct_ExN03BeamIn(void *p);
   static void streamer_ExN03BeamIn(TBuffer &buf, void *obj);

   // Function generating the singleton type initializer
   static TGenericClassInfo *GenerateInitInstanceLocal(const ::ExN03BeamIn*)
   {
      ::ExN03BeamIn *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TInstrumentedIsAProxy< ::ExN03BeamIn >(0);
      static ::ROOT::TGenericClassInfo 
         instance("ExN03BeamIn", ::ExN03BeamIn::Class_Version(), "./ExN03BeamIn.hh", 16,
                  typeid(::ExN03BeamIn), DefineBehavior(ptr, ptr),
                  &::ExN03BeamIn::Dictionary, isa_proxy, 0,
                  sizeof(::ExN03BeamIn) );
      instance.SetNew(&new_ExN03BeamIn);
      instance.SetNewArray(&newArray_ExN03BeamIn);
      instance.SetDelete(&delete_ExN03BeamIn);
      instance.SetDeleteArray(&deleteArray_ExN03BeamIn);
      instance.SetDestructor(&destruct_ExN03BeamIn);
      instance.SetStreamerFunc(&streamer_ExN03BeamIn);
      return &instance;
   }
   TGenericClassInfo *GenerateInitInstance(const ::ExN03BeamIn*)
   {
      return GenerateInitInstanceLocal((::ExN03BeamIn*)0);
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const ::ExN03BeamIn*)0x0); R__UseDummy(_R__UNIQUE_(Init));
} // end of namespace ROOT

//______________________________________________________________________________
atomic_TClass_ptr ExN03BeamIn::fgIsA(0);  // static to hold class pointer

//______________________________________________________________________________
const char *ExN03BeamIn::Class_Name()
{
   return "ExN03BeamIn";
}

//______________________________________________________________________________
const char *ExN03BeamIn::ImplFileName()
{
   return ::ROOT::GenerateInitInstanceLocal((const ::ExN03BeamIn*)0x0)->GetImplFileName();
}

//______________________________________________________________________________
int ExN03BeamIn::ImplFileLine()
{
   return ::ROOT::GenerateInitInstanceLocal((const ::ExN03BeamIn*)0x0)->GetImplFileLine();
}

//______________________________________________________________________________
void ExN03BeamIn::Dictionary()
{
   fgIsA = ::ROOT::GenerateInitInstanceLocal((const ::ExN03BeamIn*)0x0)->GetClass();
}

//______________________________________________________________________________
TClass *ExN03BeamIn::Class()
{
   if (!fgIsA) { R__LOCKGUARD2(gCINTMutex); if(!fgIsA) {fgIsA = ::ROOT::GenerateInitInstanceLocal((const ::ExN03BeamIn*)0x0)->GetClass();} }
   return fgIsA;
}

//______________________________________________________________________________
void ExN03BeamIn::Streamer(TBuffer &R__b)
{
   // Stream an object of class ExN03BeamIn.

   UInt_t R__s, R__c;
   if (R__b.IsReading()) {
      Version_t R__v = R__b.ReadVersion(&R__s, &R__c); if (R__v) { }
      TObject::Streamer(R__b);
      R__b >> MeanX;
      R__b >> SigmaX;
      R__b >> MeanY;
      R__b >> SigmaY;
      R__b >> Z0;
      R__b >> MeanMomentumX;
      R__b >> SigmaMomentumX;
      R__b >> MeanMomentumY;
      R__b >> SigmaMomentumY;
      R__b >> MomentumZ0;
      R__b >> MeanEnergy;
      R__b >> SigmaEnergy;
      R__b >> Z;
      R__b >> A;
      R__b.CheckByteCount(R__s, R__c, ExN03BeamIn::IsA());
   } else {
      R__c = R__b.WriteVersion(ExN03BeamIn::IsA(), kTRUE);
      TObject::Streamer(R__b);
      R__b << MeanX;
      R__b << SigmaX;
      R__b << MeanY;
      R__b << SigmaY;
      R__b << Z0;
      R__b << MeanMomentumX;
      R__b << SigmaMomentumX;
      R__b << MeanMomentumY;
      R__b << SigmaMomentumY;
      R__b << MomentumZ0;
      R__b << MeanEnergy;
      R__b << SigmaEnergy;
      R__b << Z;
      R__b << A;
      R__b.SetByteCount(R__c, kTRUE);
   }
}

//______________________________________________________________________________
void ExN03BeamIn::ShowMembers(TMemberInspector &R__insp)
{
      // Inspect the data members of an object of class ExN03BeamIn.
      TClass *R__cl = ::ExN03BeamIn::IsA();
      if (R__cl || R__insp.IsA()) { }
      R__insp.Inspect(R__cl, R__insp.GetParent(), "MeanX", &MeanX);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "SigmaX", &SigmaX);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "MeanY", &MeanY);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "SigmaY", &SigmaY);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "Z0", &Z0);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "MeanMomentumX", &MeanMomentumX);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "SigmaMomentumX", &SigmaMomentumX);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "MeanMomentumY", &MeanMomentumY);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "SigmaMomentumY", &SigmaMomentumY);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "MomentumZ0", &MomentumZ0);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "MeanEnergy", &MeanEnergy);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "SigmaEnergy", &SigmaEnergy);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "Z", &Z);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "A", &A);
      TObject::ShowMembers(R__insp);
}

namespace ROOT {
   // Wrappers around operator new
   static void *new_ExN03BeamIn(void *p) {
      return  p ? new(p) ::ExN03BeamIn : new ::ExN03BeamIn;
   }
   static void *newArray_ExN03BeamIn(Long_t nElements, void *p) {
      return p ? new(p) ::ExN03BeamIn[nElements] : new ::ExN03BeamIn[nElements];
   }
   // Wrapper around operator delete
   static void delete_ExN03BeamIn(void *p) {
      delete ((::ExN03BeamIn*)p);
   }
   static void deleteArray_ExN03BeamIn(void *p) {
      delete [] ((::ExN03BeamIn*)p);
   }
   static void destruct_ExN03BeamIn(void *p) {
      typedef ::ExN03BeamIn current_t;
      ((current_t*)p)->~current_t();
   }
   // Wrapper around a custom streamer member function.
   static void streamer_ExN03BeamIn(TBuffer &buf, void *obj) {
      ((::ExN03BeamIn*)obj)->::ExN03BeamIn::Streamer(buf);
   }
} // end of namespace ROOT for class ::ExN03BeamIn

/********************************************************
* ExN03BeamInDict.cxx
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************/

#ifdef G__MEMTEST
#undef malloc
#undef free
#endif

#if defined(__GNUC__) && __GNUC__ >= 4 && ((__GNUC_MINOR__ == 2 && __GNUC_PATCHLEVEL__ >= 1) || (__GNUC_MINOR__ >= 3))
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif

extern "C" void G__cpp_reset_tagtableExN03BeamInDict();

extern "C" void G__set_cpp_environmentExN03BeamInDict() {
  G__add_compiledheader("TObject.h");
  G__add_compiledheader("TMemberInspector.h");
  G__add_compiledheader("ExN03BeamIn.hh");
  G__cpp_reset_tagtableExN03BeamInDict();
}
#include <new>
extern "C" int G__cpp_dllrevExN03BeamInDict() { return(30051515); }

/*********************************************************
* Member function Interface Method
*********************************************************/

/* ExN03BeamIn */
static int G__ExN03BeamInDict_184_0_1(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   ExN03BeamIn* p = NULL;
   char* gvp = (char*) G__getgvp();
   int n = G__getaryconstruct();
   if (n) {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new ExN03BeamIn[n];
     } else {
       p = new((void*) gvp) ExN03BeamIn[n];
     }
   } else {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new ExN03BeamIn;
     } else {
       p = new((void*) gvp) ExN03BeamIn;
     }
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__ExN03BeamInDictLN_ExN03BeamIn));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__ExN03BeamInDict_184_0_2(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((ExN03BeamIn*) G__getstructoffset())->ReadConfigurationFile(*((string*) G__int(libp->para[0])));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__ExN03BeamInDict_184_0_3(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) ExN03BeamIn::Class());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__ExN03BeamInDict_184_0_4(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) ExN03BeamIn::Class_Name());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__ExN03BeamInDict_184_0_5(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 115, (long) ExN03BeamIn::Class_Version());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__ExN03BeamInDict_184_0_6(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ExN03BeamIn::Dictionary();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__ExN03BeamInDict_184_0_10(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((ExN03BeamIn*) G__getstructoffset())->StreamerNVirtual(*(TBuffer*) libp->para[0].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__ExN03BeamInDict_184_0_11(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) ExN03BeamIn::DeclFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__ExN03BeamInDict_184_0_12(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ExN03BeamIn::ImplFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__ExN03BeamInDict_184_0_13(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) ExN03BeamIn::ImplFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__ExN03BeamInDict_184_0_14(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ExN03BeamIn::DeclFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic copy constructor
static int G__ExN03BeamInDict_184_0_15(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)

{
   ExN03BeamIn* p;
   void* tmp = (void*) G__int(libp->para[0]);
   p = new ExN03BeamIn(*(ExN03BeamIn*) tmp);
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__ExN03BeamInDictLN_ExN03BeamIn));
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef ExN03BeamIn G__TExN03BeamIn;
static int G__ExN03BeamInDict_184_0_16(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   char* gvp = (char*) G__getgvp();
   long soff = G__getstructoffset();
   int n = G__getaryconstruct();
   //
   //has_a_delete: 1
   //has_own_delete1arg: 0
   //has_own_delete2arg: 0
   //
   if (!soff) {
     return(1);
   }
   if (n) {
     if (gvp == (char*)G__PVOID) {
       delete[] (ExN03BeamIn*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       for (int i = n - 1; i >= 0; --i) {
         ((ExN03BeamIn*) (soff+(sizeof(ExN03BeamIn)*i)))->~G__TExN03BeamIn();
       }
       G__setgvp((long)gvp);
     }
   } else {
     if (gvp == (char*)G__PVOID) {
       delete (ExN03BeamIn*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       ((ExN03BeamIn*) (soff))->~G__TExN03BeamIn();
       G__setgvp((long)gvp);
     }
   }
   G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic assignment operator
static int G__ExN03BeamInDict_184_0_17(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   ExN03BeamIn* dest = (ExN03BeamIn*) G__getstructoffset();
   *dest = *(ExN03BeamIn*) libp->para[0].ref;
   const ExN03BeamIn& obj = *dest;
   result7->ref = (long) (&obj);
   result7->obj.i = (long) (&obj);
   return(1 || funcname || hash || result7 || libp) ;
}


/* Setting up global function */

/*********************************************************
* Member function Stub
*********************************************************/

/* ExN03BeamIn */

/*********************************************************
* Global function Stub
*********************************************************/

/*********************************************************
* Get size of pointer to member function
*********************************************************/
class G__Sizep2memfuncExN03BeamInDict {
 public:
  G__Sizep2memfuncExN03BeamInDict(): p(&G__Sizep2memfuncExN03BeamInDict::sizep2memfunc) {}
    size_t sizep2memfunc() { return(sizeof(p)); }
  private:
    size_t (G__Sizep2memfuncExN03BeamInDict::*p)();
};

size_t G__get_sizep2memfuncExN03BeamInDict()
{
  G__Sizep2memfuncExN03BeamInDict a;
  G__setsizep2memfunc((int)a.sizep2memfunc());
  return((size_t)a.sizep2memfunc());
}


/*********************************************************
* virtual base class offset calculation interface
*********************************************************/

   /* Setting up class inheritance */

/*********************************************************
* Inheritance information setup/
*********************************************************/
extern "C" void G__cpp_setup_inheritanceExN03BeamInDict() {

   /* Setting up class inheritance */
   if(0==G__getnumbaseclass(G__get_linked_tagnum(&G__ExN03BeamInDictLN_ExN03BeamIn))) {
     ExN03BeamIn *G__Lderived;
     G__Lderived=(ExN03BeamIn*)0x1000;
     {
       TObject *G__Lpbase=(TObject*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__ExN03BeamInDictLN_ExN03BeamIn),G__get_linked_tagnum(&G__ExN03BeamInDictLN_TObject),(long)G__Lpbase-(long)G__Lderived,1,1);
     }
   }
}

/*********************************************************
* typedef information setup/
*********************************************************/
extern "C" void G__cpp_setup_typetableExN03BeamInDict() {

   /* Setting up typedef entry */
   G__search_typename2("Version_t",115,-1,0,-1);
   G__setnewtype(-1,"Class version identifier (short)",0);
   G__search_typename2("vector<ROOT::TSchemaHelper>",117,G__get_linked_tagnum(&G__ExN03BeamInDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__ExN03BeamInDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__ExN03BeamInDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__ExN03BeamInDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__ExN03BeamInDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TVirtualArray*>",117,G__get_linked_tagnum(&G__ExN03BeamInDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__ExN03BeamInDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__ExN03BeamInDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__ExN03BeamInDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__ExN03BeamInDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
}

/*********************************************************
* Data Member information setup/
*********************************************************/

   /* Setting up class,struct,union tag member variable */

   /* ExN03BeamIn */
static void G__setup_memvarExN03BeamIn(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__ExN03BeamInDictLN_ExN03BeamIn));
   { ExN03BeamIn *p; p=(ExN03BeamIn*)0x1000; if (p) { }
   G__memvar_setup((void*)((long)(&p->MeanX)-(long)(p)),100,0,0,-1,-1,-1,1,"MeanX=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->SigmaX)-(long)(p)),100,0,0,-1,-1,-1,1,"SigmaX=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->MeanY)-(long)(p)),100,0,0,-1,-1,-1,1,"MeanY=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->SigmaY)-(long)(p)),100,0,0,-1,-1,-1,1,"SigmaY=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->Z0)-(long)(p)),100,0,0,-1,-1,-1,1,"Z0=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->MeanMomentumX)-(long)(p)),100,0,0,-1,-1,-1,1,"MeanMomentumX=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->SigmaMomentumX)-(long)(p)),100,0,0,-1,-1,-1,1,"SigmaMomentumX=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->MeanMomentumY)-(long)(p)),100,0,0,-1,-1,-1,1,"MeanMomentumY=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->SigmaMomentumY)-(long)(p)),100,0,0,-1,-1,-1,1,"SigmaMomentumY=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->MomentumZ0)-(long)(p)),100,0,0,-1,-1,-1,1,"MomentumZ0=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->MeanEnergy)-(long)(p)),100,0,0,-1,-1,-1,1,"MeanEnergy=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->SigmaEnergy)-(long)(p)),100,0,0,-1,-1,-1,1,"SigmaEnergy=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->Z)-(long)(p)),105,0,0,-1,-1,-1,1,"Z=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->A)-(long)(p)),105,0,0,-1,-1,-1,1,"A=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__ExN03BeamInDictLN_TClass),G__defined_typename("atomic_TClass_ptr"),-2,4,"fgIsA=",0,(char*)NULL);
   }
   G__tag_memvar_reset();
}

extern "C" void G__cpp_setup_memvarExN03BeamInDict() {
}
/***********************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
***********************************************************/

/*********************************************************
* Member function information setup for each class
*********************************************************/
static void G__setup_memfuncExN03BeamIn(void) {
   /* ExN03BeamIn */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__ExN03BeamInDictLN_ExN03BeamIn));
   G__memfunc_setup("ExN03BeamIn",922,G__ExN03BeamInDict_184_0_1, 105, G__get_linked_tagnum(&G__ExN03BeamInDictLN_ExN03BeamIn), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("ReadConfigurationFile",2132,G__ExN03BeamInDict_184_0_2, 121, -1, -1, 0, 1, 1, 1, 0, "u 'string' - 0 - -", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Class",502,G__ExN03BeamInDict_184_0_3, 85, G__get_linked_tagnum(&G__ExN03BeamInDictLN_TClass), -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (TClass* (*)())(&ExN03BeamIn::Class) ), 0);
   G__memfunc_setup("Class_Name",982,G__ExN03BeamInDict_184_0_4, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&ExN03BeamIn::Class_Name) ), 0);
   G__memfunc_setup("Class_Version",1339,G__ExN03BeamInDict_184_0_5, 115, -1, G__defined_typename("Version_t"), 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (Version_t (*)())(&ExN03BeamIn::Class_Version) ), 0);
   G__memfunc_setup("Dictionary",1046,G__ExN03BeamInDict_184_0_6, 121, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (void (*)())(&ExN03BeamIn::Dictionary) ), 0);
   G__memfunc_setup("IsA",253,(G__InterfaceMethod) NULL,85, G__get_linked_tagnum(&G__ExN03BeamInDictLN_TClass), -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("ShowMembers",1132,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TMemberInspector' - 1 - -", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Streamer",835,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - -", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("StreamerNVirtual",1656,G__ExN03BeamInDict_184_0_10, 121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - ClassDef_StreamerNVirtual_b", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DeclFileName",1145,G__ExN03BeamInDict_184_0_11, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&ExN03BeamIn::DeclFileName) ), 0);
   G__memfunc_setup("ImplFileLine",1178,G__ExN03BeamInDict_184_0_12, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&ExN03BeamIn::ImplFileLine) ), 0);
   G__memfunc_setup("ImplFileName",1171,G__ExN03BeamInDict_184_0_13, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&ExN03BeamIn::ImplFileName) ), 0);
   G__memfunc_setup("DeclFileLine",1152,G__ExN03BeamInDict_184_0_14, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&ExN03BeamIn::DeclFileLine) ), 0);
   // automatic copy constructor
   G__memfunc_setup("ExN03BeamIn", 922, G__ExN03BeamInDict_184_0_15, (int) ('i'), G__get_linked_tagnum(&G__ExN03BeamInDictLN_ExN03BeamIn), -1, 0, 1, 1, 1, 0, "u 'ExN03BeamIn' - 11 - -", (char*) NULL, (void*) NULL, 0);
   // automatic destructor
   G__memfunc_setup("~ExN03BeamIn", 1048, G__ExN03BeamInDict_184_0_16, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 1);
   // automatic assignment operator
   G__memfunc_setup("operator=", 937, G__ExN03BeamInDict_184_0_17, (int) ('u'), G__get_linked_tagnum(&G__ExN03BeamInDictLN_ExN03BeamIn), -1, 1, 1, 1, 1, 0, "u 'ExN03BeamIn' - 11 - -", (char*) NULL, (void*) NULL, 0);
   G__tag_memfunc_reset();
}


/*********************************************************
* Member function information setup
*********************************************************/
extern "C" void G__cpp_setup_memfuncExN03BeamInDict() {
}

/*********************************************************
* Global variable information setup for each class
*********************************************************/
static void G__cpp_setup_global0() {

   /* Setting up global variables */
   G__resetplocal();

}

static void G__cpp_setup_global1() {
}

static void G__cpp_setup_global2() {

   G__resetglobalenv();
}
extern "C" void G__cpp_setup_globalExN03BeamInDict() {
  G__cpp_setup_global0();
  G__cpp_setup_global1();
  G__cpp_setup_global2();
}

/*********************************************************
* Global function information setup for each class
*********************************************************/
static void G__cpp_setup_func0() {
   G__lastifuncposition();

}

static void G__cpp_setup_func1() {
}

static void G__cpp_setup_func2() {
}

static void G__cpp_setup_func3() {
}

static void G__cpp_setup_func4() {
}

static void G__cpp_setup_func5() {
}

static void G__cpp_setup_func6() {
}

static void G__cpp_setup_func7() {
}

static void G__cpp_setup_func8() {
}

static void G__cpp_setup_func9() {
}

static void G__cpp_setup_func10() {
}

static void G__cpp_setup_func11() {
}

static void G__cpp_setup_func12() {
}

static void G__cpp_setup_func13() {

   G__resetifuncposition();
}

extern "C" void G__cpp_setup_funcExN03BeamInDict() {
  G__cpp_setup_func0();
  G__cpp_setup_func1();
  G__cpp_setup_func2();
  G__cpp_setup_func3();
  G__cpp_setup_func4();
  G__cpp_setup_func5();
  G__cpp_setup_func6();
  G__cpp_setup_func7();
  G__cpp_setup_func8();
  G__cpp_setup_func9();
  G__cpp_setup_func10();
  G__cpp_setup_func11();
  G__cpp_setup_func12();
  G__cpp_setup_func13();
}

/*********************************************************
* Class,struct,union,enum tag information setup
*********************************************************/
/* Setup class/struct taginfo */
G__linked_taginfo G__ExN03BeamInDictLN_TClass = { "TClass" , 99 , -1 };
G__linked_taginfo G__ExN03BeamInDictLN_TBuffer = { "TBuffer" , 99 , -1 };
G__linked_taginfo G__ExN03BeamInDictLN_TMemberInspector = { "TMemberInspector" , 99 , -1 };
G__linked_taginfo G__ExN03BeamInDictLN_TObject = { "TObject" , 99 , -1 };
G__linked_taginfo G__ExN03BeamInDictLN_string = { "string" , 99 , -1 };
G__linked_taginfo G__ExN03BeamInDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR = { "vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >" , 99 , -1 };
G__linked_taginfo G__ExN03BeamInDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR = { "reverse_iterator<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::iterator>" , 99 , -1 };
G__linked_taginfo G__ExN03BeamInDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR = { "vector<TVirtualArray*,allocator<TVirtualArray*> >" , 99 , -1 };
G__linked_taginfo G__ExN03BeamInDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TVirtualArray*,allocator<TVirtualArray*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__ExN03BeamInDictLN_ExN03BeamIn = { "ExN03BeamIn" , 99 , -1 };

/* Reset class/struct taginfo */
extern "C" void G__cpp_reset_tagtableExN03BeamInDict() {
  G__ExN03BeamInDictLN_TClass.tagnum = -1 ;
  G__ExN03BeamInDictLN_TBuffer.tagnum = -1 ;
  G__ExN03BeamInDictLN_TMemberInspector.tagnum = -1 ;
  G__ExN03BeamInDictLN_TObject.tagnum = -1 ;
  G__ExN03BeamInDictLN_string.tagnum = -1 ;
  G__ExN03BeamInDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR.tagnum = -1 ;
  G__ExN03BeamInDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__ExN03BeamInDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR.tagnum = -1 ;
  G__ExN03BeamInDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__ExN03BeamInDictLN_ExN03BeamIn.tagnum = -1 ;
}


extern "C" void G__cpp_setup_tagtableExN03BeamInDict() {

   /* Setting up class,struct,union tag entry */
   G__get_linked_tagnum_fwd(&G__ExN03BeamInDictLN_TClass);
   G__get_linked_tagnum_fwd(&G__ExN03BeamInDictLN_TBuffer);
   G__get_linked_tagnum_fwd(&G__ExN03BeamInDictLN_TMemberInspector);
   G__get_linked_tagnum_fwd(&G__ExN03BeamInDictLN_TObject);
   G__get_linked_tagnum_fwd(&G__ExN03BeamInDictLN_string);
   G__get_linked_tagnum_fwd(&G__ExN03BeamInDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR);
   G__get_linked_tagnum_fwd(&G__ExN03BeamInDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__ExN03BeamInDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR);
   G__get_linked_tagnum_fwd(&G__ExN03BeamInDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR);
   G__tagtable_setup(G__get_linked_tagnum_fwd(&G__ExN03BeamInDictLN_ExN03BeamIn),sizeof(ExN03BeamIn),-1,29952,(char*)NULL,G__setup_memvarExN03BeamIn,G__setup_memfuncExN03BeamIn);
}
extern "C" void G__cpp_setupExN03BeamInDict(void) {
  G__check_setup_version(30051515,"G__cpp_setupExN03BeamInDict()");
  G__set_cpp_environmentExN03BeamInDict();
  G__cpp_setup_tagtableExN03BeamInDict();

  G__cpp_setup_inheritanceExN03BeamInDict();

  G__cpp_setup_typetableExN03BeamInDict();

  G__cpp_setup_memvarExN03BeamInDict();

  G__cpp_setup_memfuncExN03BeamInDict();
  G__cpp_setup_globalExN03BeamInDict();
  G__cpp_setup_funcExN03BeamInDict();

   if(0==G__getsizep2memfunc()) G__get_sizep2memfuncExN03BeamInDict();
  return;
}
class G__cpp_setup_initExN03BeamInDict {
  public:
    G__cpp_setup_initExN03BeamInDict() { G__add_setup_func("ExN03BeamInDict",(G__incsetup)(&G__cpp_setupExN03BeamInDict)); G__call_setup_funcs(); }
   ~G__cpp_setup_initExN03BeamInDict() { G__remove_setup_func("ExN03BeamInDict"); }
};
G__cpp_setup_initExN03BeamInDict G__cpp_setup_initializerExN03BeamInDict;

