//
// File generated by rootcint at Wed Feb 22 17:24:38 2017

// Do NOT change. Changes will be lost next time file is generated
//

#define R__DICTIONARY_FILENAME ExN03DataoDictRings
#include "RConfig.h" //rootcint 4834
#if !defined(R__ACCESS_IN_SYMBOL)
//Break the privacy of classes -- Disabled for the moment
#define private public
#define protected public
#endif

// Since CINT ignores the std namespace, we need to do so in this file.
namespace std {} using namespace std;
#include "ExN03DataoDictRings.h"

#include "TCollectionProxyInfo.h"
#include "TClass.h"
#include "TBuffer.h"
#include "TMemberInspector.h"
#include "TError.h"

#ifndef G__ROOT
#define G__ROOT
#endif

#include "RtypesImp.h"
#include "TIsAProxy.h"
#include "TFileMergeInfo.h"

// START OF SHADOWS

namespace ROOT {
   namespace Shadow {
   } // of namespace Shadow
} // of namespace ROOT
// END OF SHADOWS

namespace ROOT {
   void ExN03DataoRings_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void *new_ExN03DataoRings(void *p = 0);
   static void *newArray_ExN03DataoRings(Long_t size, void *p);
   static void delete_ExN03DataoRings(void *p);
   static void deleteArray_ExN03DataoRings(void *p);
   static void destruct_ExN03DataoRings(void *p);
   static void streamer_ExN03DataoRings(TBuffer &buf, void *obj);

   // Function generating the singleton type initializer
   static TGenericClassInfo *GenerateInitInstanceLocal(const ::ExN03DataoRings*)
   {
      ::ExN03DataoRings *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TInstrumentedIsAProxy< ::ExN03DataoRings >(0);
      static ::ROOT::TGenericClassInfo 
         instance("ExN03DataoRings", ::ExN03DataoRings::Class_Version(), "./ExN03DataoRings.hh", 18,
                  typeid(::ExN03DataoRings), DefineBehavior(ptr, ptr),
                  &::ExN03DataoRings::Dictionary, isa_proxy, 0,
                  sizeof(::ExN03DataoRings) );
      instance.SetNew(&new_ExN03DataoRings);
      instance.SetNewArray(&newArray_ExN03DataoRings);
      instance.SetDelete(&delete_ExN03DataoRings);
      instance.SetDeleteArray(&deleteArray_ExN03DataoRings);
      instance.SetDestructor(&destruct_ExN03DataoRings);
      instance.SetStreamerFunc(&streamer_ExN03DataoRings);
      return &instance;
   }
   TGenericClassInfo *GenerateInitInstance(const ::ExN03DataoRings*)
   {
      return GenerateInitInstanceLocal((::ExN03DataoRings*)0);
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const ::ExN03DataoRings*)0x0); R__UseDummy(_R__UNIQUE_(Init));
} // end of namespace ROOT

//______________________________________________________________________________
TClass *ExN03DataoRings::fgIsA = 0;  // static to hold class pointer

//______________________________________________________________________________
const char *ExN03DataoRings::Class_Name()
{
   return "ExN03DataoRings";
}

//______________________________________________________________________________
const char *ExN03DataoRings::ImplFileName()
{
   return ::ROOT::GenerateInitInstanceLocal((const ::ExN03DataoRings*)0x0)->GetImplFileName();
}

//______________________________________________________________________________
int ExN03DataoRings::ImplFileLine()
{
   return ::ROOT::GenerateInitInstanceLocal((const ::ExN03DataoRings*)0x0)->GetImplFileLine();
}

//______________________________________________________________________________
void ExN03DataoRings::Dictionary()
{
   fgIsA = ::ROOT::GenerateInitInstanceLocal((const ::ExN03DataoRings*)0x0)->GetClass();
}

//______________________________________________________________________________
TClass *ExN03DataoRings::Class()
{
   if (!fgIsA) fgIsA = ::ROOT::GenerateInitInstanceLocal((const ::ExN03DataoRings*)0x0)->GetClass();
   return fgIsA;
}

//______________________________________________________________________________
void ExN03DataoRings::Streamer(TBuffer &R__b)
{
   // Stream an object of class ExN03DataoRings.

   UInt_t R__s, R__c;
   if (R__b.IsReading()) {
      Version_t R__v = R__b.ReadVersion(&R__s, &R__c); if (R__v) { }
      TObject::Streamer(R__b);
      datai.Streamer(R__b);
      {
         vector<double> &R__stl =  x_pad;
         R__stl.clear();
         int R__i, R__n;
         R__b >> R__n;
         R__stl.reserve(R__n);
         for (R__i = 0; R__i < R__n; R__i++) {
            double R__t;
            R__b >> R__t;
            R__stl.push_back(R__t);
         }
      }
      {
         vector<double> &R__stl =  y_pad;
         R__stl.clear();
         int R__i, R__n;
         R__b >> R__n;
         R__stl.reserve(R__n);
         for (R__i = 0; R__i < R__n; R__i++) {
            double R__t;
            R__b >> R__t;
            R__stl.push_back(R__t);
         }
      }
      {
         vector<double> &R__stl =  t_pad;
         R__stl.clear();
         int R__i, R__n;
         R__b >> R__n;
         R__stl.reserve(R__n);
         for (R__i = 0; R__i < R__n; R__i++) {
            double R__t;
            R__b >> R__t;
            R__stl.push_back(R__t);
         }
      }
      {
         vector<double> &R__stl =  dt;
         R__stl.clear();
         int R__i, R__n;
         R__b >> R__n;
         R__stl.reserve(R__n);
         for (R__i = 0; R__i < R__n; R__i++) {
            double R__t;
            R__b >> R__t;
            R__stl.push_back(R__t);
         }
      }
      {
         vector<double> &R__stl =  q_pad;
         R__stl.clear();
         int R__i, R__n;
         R__b >> R__n;
         R__stl.reserve(R__n);
         for (R__i = 0; R__i < R__n; R__i++) {
            double R__t;
            R__b >> R__t;
            R__stl.push_back(R__t);
         }
      }
      R__b >> Et_pad;
      R__b >> nb_pads;
      R__b >> NRings;
      R__b >> NSegments;
      R__b >> sigL;
      R__b >> sigT;
      R__b >> driftV;
      R__b >> Ionis;
      R__b >> TimeBinSize;
      R__b >> ShapingTime;
      R__b >> Threshold;
      R__b >> Gain;
      R__b >> NoiseRMS;
      R__b >> Theta;
      R__b >> FirstRing;
      R__b >> LastRing;
      R__b.CheckByteCount(R__s, R__c, ExN03DataoRings::IsA());
   } else {
      R__c = R__b.WriteVersion(ExN03DataoRings::IsA(), kTRUE);
      TObject::Streamer(R__b);
      datai.Streamer(R__b);
      {
         vector<double> &R__stl =  x_pad;
         int R__n=(&R__stl) ? int(R__stl.size()) : 0;
         R__b << R__n;
         if(R__n) {
            vector<double>::iterator R__k;
            for (R__k = R__stl.begin(); R__k != R__stl.end(); ++R__k) {
            R__b << (*R__k);
            }
         }
      }
      {
         vector<double> &R__stl =  y_pad;
         int R__n=(&R__stl) ? int(R__stl.size()) : 0;
         R__b << R__n;
         if(R__n) {
            vector<double>::iterator R__k;
            for (R__k = R__stl.begin(); R__k != R__stl.end(); ++R__k) {
            R__b << (*R__k);
            }
         }
      }
      {
         vector<double> &R__stl =  t_pad;
         int R__n=(&R__stl) ? int(R__stl.size()) : 0;
         R__b << R__n;
         if(R__n) {
            vector<double>::iterator R__k;
            for (R__k = R__stl.begin(); R__k != R__stl.end(); ++R__k) {
            R__b << (*R__k);
            }
         }
      }
      {
         vector<double> &R__stl =  dt;
         int R__n=(&R__stl) ? int(R__stl.size()) : 0;
         R__b << R__n;
         if(R__n) {
            vector<double>::iterator R__k;
            for (R__k = R__stl.begin(); R__k != R__stl.end(); ++R__k) {
            R__b << (*R__k);
            }
         }
      }
      {
         vector<double> &R__stl =  q_pad;
         int R__n=(&R__stl) ? int(R__stl.size()) : 0;
         R__b << R__n;
         if(R__n) {
            vector<double>::iterator R__k;
            for (R__k = R__stl.begin(); R__k != R__stl.end(); ++R__k) {
            R__b << (*R__k);
            }
         }
      }
      R__b << Et_pad;
      R__b << nb_pads;
      R__b << NRings;
      R__b << NSegments;
      R__b << sigL;
      R__b << sigT;
      R__b << driftV;
      R__b << Ionis;
      R__b << TimeBinSize;
      R__b << ShapingTime;
      R__b << Threshold;
      R__b << Gain;
      R__b << NoiseRMS;
      R__b << Theta;
      R__b << FirstRing;
      R__b << LastRing;
      R__b.SetByteCount(R__c, kTRUE);
   }
}

//______________________________________________________________________________
void ExN03DataoRings::ShowMembers(TMemberInspector &R__insp)
{
      // Inspect the data members of an object of class ExN03DataoRings.
      TClass *R__cl = ::ExN03DataoRings::IsA();
      if (R__cl || R__insp.IsA()) { }
      R__insp.Inspect(R__cl, R__insp.GetParent(), "datai", &datai);
      R__insp.InspectMember(datai, "datai.");
      R__insp.Inspect(R__cl, R__insp.GetParent(), "x_pad", (void*)&x_pad);
      R__insp.InspectMember("vector<double>", (void*)&x_pad, "x_pad.", false);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "y_pad", (void*)&y_pad);
      R__insp.InspectMember("vector<double>", (void*)&y_pad, "y_pad.", false);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "t_pad", (void*)&t_pad);
      R__insp.InspectMember("vector<double>", (void*)&t_pad, "t_pad.", false);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "dt", (void*)&dt);
      R__insp.InspectMember("vector<double>", (void*)&dt, "dt.", false);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "q_pad", (void*)&q_pad);
      R__insp.InspectMember("vector<double>", (void*)&q_pad, "q_pad.", false);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "Et_pad", &Et_pad);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "nb_pads", &nb_pads);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "NRings", &NRings);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "NSegments", &NSegments);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "sigL", &sigL);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "sigT", &sigT);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "driftV", &driftV);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "Ionis", &Ionis);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "TimeBinSize", &TimeBinSize);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "ShapingTime", &ShapingTime);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "Threshold", &Threshold);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "Gain", &Gain);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "NoiseRMS", &NoiseRMS);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "Theta", &Theta);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "FirstRing", &FirstRing);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "LastRing", &LastRing);
      TObject::ShowMembers(R__insp);
}

namespace ROOT {
   // Wrappers around operator new
   static void *new_ExN03DataoRings(void *p) {
      return  p ? new(p) ::ExN03DataoRings : new ::ExN03DataoRings;
   }
   static void *newArray_ExN03DataoRings(Long_t nElements, void *p) {
      return p ? new(p) ::ExN03DataoRings[nElements] : new ::ExN03DataoRings[nElements];
   }
   // Wrapper around operator delete
   static void delete_ExN03DataoRings(void *p) {
      delete ((::ExN03DataoRings*)p);
   }
   static void deleteArray_ExN03DataoRings(void *p) {
      delete [] ((::ExN03DataoRings*)p);
   }
   static void destruct_ExN03DataoRings(void *p) {
      typedef ::ExN03DataoRings current_t;
      ((current_t*)p)->~current_t();
   }
   // Wrapper around a custom streamer member function.
   static void streamer_ExN03DataoRings(TBuffer &buf, void *obj) {
      ((::ExN03DataoRings*)obj)->::ExN03DataoRings::Streamer(buf);
   }
} // end of namespace ROOT for class ::ExN03DataoRings

namespace ROOT {
   void vectorlEdoublegR_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void vectorlEdoublegR_Dictionary();
   static void *new_vectorlEdoublegR(void *p = 0);
   static void *newArray_vectorlEdoublegR(Long_t size, void *p);
   static void delete_vectorlEdoublegR(void *p);
   static void deleteArray_vectorlEdoublegR(void *p);
   static void destruct_vectorlEdoublegR(void *p);

   // Function generating the singleton type initializer
   static TGenericClassInfo *GenerateInitInstanceLocal(const vector<double>*)
   {
      vector<double> *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TIsAProxy(typeid(vector<double>),0);
      static ::ROOT::TGenericClassInfo 
         instance("vector<double>", -2, "vector.dll", 0,
                  typeid(vector<double>), DefineBehavior(ptr, ptr),
                  0, &vectorlEdoublegR_Dictionary, isa_proxy, 0,
                  sizeof(vector<double>) );
      instance.SetNew(&new_vectorlEdoublegR);
      instance.SetNewArray(&newArray_vectorlEdoublegR);
      instance.SetDelete(&delete_vectorlEdoublegR);
      instance.SetDeleteArray(&deleteArray_vectorlEdoublegR);
      instance.SetDestructor(&destruct_vectorlEdoublegR);
      instance.AdoptCollectionProxyInfo(TCollectionProxyInfo::Generate(TCollectionProxyInfo::Pushback< vector<double> >()));
      return &instance;
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const vector<double>*)0x0); R__UseDummy(_R__UNIQUE_(Init));

   // Dictionary for non-ClassDef classes
   static void vectorlEdoublegR_Dictionary() {
      ::ROOT::GenerateInitInstanceLocal((const vector<double>*)0x0)->GetClass();
   }

} // end of namespace ROOT

namespace ROOT {
   // Wrappers around operator new
   static void *new_vectorlEdoublegR(void *p) {
      return  p ? ::new((::ROOT::TOperatorNewHelper*)p) vector<double> : new vector<double>;
   }
   static void *newArray_vectorlEdoublegR(Long_t nElements, void *p) {
      return p ? ::new((::ROOT::TOperatorNewHelper*)p) vector<double>[nElements] : new vector<double>[nElements];
   }
   // Wrapper around operator delete
   static void delete_vectorlEdoublegR(void *p) {
      delete ((vector<double>*)p);
   }
   static void deleteArray_vectorlEdoublegR(void *p) {
      delete [] ((vector<double>*)p);
   }
   static void destruct_vectorlEdoublegR(void *p) {
      typedef vector<double> current_t;
      ((current_t*)p)->~current_t();
   }
} // end of namespace ROOT for class vector<double>

/********************************************************
* ExN03DataoDictRings.cxx
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************/

#ifdef G__MEMTEST
#undef malloc
#undef free
#endif

#if defined(__GNUC__) && __GNUC__ >= 4 && ((__GNUC_MINOR__ == 2 && __GNUC_PATCHLEVEL__ >= 1) || (__GNUC_MINOR__ >= 3))
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif

extern "C" void G__cpp_reset_tagtableExN03DataoDictRings();

extern "C" void G__set_cpp_environmentExN03DataoDictRings() {
  G__add_compiledheader("TObject.h");
  G__add_compiledheader("TMemberInspector.h");
  G__add_compiledheader("ExN03DataoRings.hh");
  G__cpp_reset_tagtableExN03DataoDictRings();
}
#include <new>
extern "C" int G__cpp_dllrevExN03DataoDictRings() { return(30051515); }

/*********************************************************
* Member function Interface Method
*********************************************************/

/* ExN03DataoRings */
static int G__ExN03DataoDictRings_189_0_1(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   ExN03DataoRings* p = NULL;
   char* gvp = (char*) G__getgvp();
   int n = G__getaryconstruct();
   if (n) {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new ExN03DataoRings[n];
     } else {
       p = new((void*) gvp) ExN03DataoRings[n];
     }
   } else {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new ExN03DataoRings;
     } else {
       p = new((void*) gvp) ExN03DataoRings;
     }
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__ExN03DataoDictRingsLN_ExN03DataoRings));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__ExN03DataoDictRings_189_0_2(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((ExN03DataoRings*) G__getstructoffset())->ClearEvent();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__ExN03DataoDictRings_189_0_3(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((ExN03DataoRings*) G__getstructoffset())->ReadConfigurationFile(*((string*) G__int(libp->para[0])));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__ExN03DataoDictRings_189_0_4(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) ExN03DataoRings::Class());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__ExN03DataoDictRings_189_0_5(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) ExN03DataoRings::Class_Name());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__ExN03DataoDictRings_189_0_6(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 115, (long) ExN03DataoRings::Class_Version());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__ExN03DataoDictRings_189_0_7(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ExN03DataoRings::Dictionary();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__ExN03DataoDictRings_189_0_11(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((ExN03DataoRings*) G__getstructoffset())->StreamerNVirtual(*(TBuffer*) libp->para[0].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__ExN03DataoDictRings_189_0_12(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) ExN03DataoRings::DeclFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__ExN03DataoDictRings_189_0_13(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ExN03DataoRings::ImplFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__ExN03DataoDictRings_189_0_14(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) ExN03DataoRings::ImplFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__ExN03DataoDictRings_189_0_15(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ExN03DataoRings::DeclFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic copy constructor
static int G__ExN03DataoDictRings_189_0_16(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)

{
   ExN03DataoRings* p;
   void* tmp = (void*) G__int(libp->para[0]);
   p = new ExN03DataoRings(*(ExN03DataoRings*) tmp);
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__ExN03DataoDictRingsLN_ExN03DataoRings));
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef ExN03DataoRings G__TExN03DataoRings;
static int G__ExN03DataoDictRings_189_0_17(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   char* gvp = (char*) G__getgvp();
   long soff = G__getstructoffset();
   int n = G__getaryconstruct();
   //
   //has_a_delete: 1
   //has_own_delete1arg: 0
   //has_own_delete2arg: 0
   //
   if (!soff) {
     return(1);
   }
   if (n) {
     if (gvp == (char*)G__PVOID) {
       delete[] (ExN03DataoRings*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       for (int i = n - 1; i >= 0; --i) {
         ((ExN03DataoRings*) (soff+(sizeof(ExN03DataoRings)*i)))->~G__TExN03DataoRings();
       }
       G__setgvp((long)gvp);
     }
   } else {
     if (gvp == (char*)G__PVOID) {
       delete (ExN03DataoRings*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       ((ExN03DataoRings*) (soff))->~G__TExN03DataoRings();
       G__setgvp((long)gvp);
     }
   }
   G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic assignment operator
static int G__ExN03DataoDictRings_189_0_18(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   ExN03DataoRings* dest = (ExN03DataoRings*) G__getstructoffset();
   *dest = *(ExN03DataoRings*) libp->para[0].ref;
   const ExN03DataoRings& obj = *dest;
   result7->ref = (long) (&obj);
   result7->obj.i = (long) (&obj);
   return(1 || funcname || hash || result7 || libp) ;
}


/* Setting up global function */

/*********************************************************
* Member function Stub
*********************************************************/

/* ExN03DataoRings */

/*********************************************************
* Global function Stub
*********************************************************/

/*********************************************************
* Get size of pointer to member function
*********************************************************/
class G__Sizep2memfuncExN03DataoDictRings {
 public:
  G__Sizep2memfuncExN03DataoDictRings(): p(&G__Sizep2memfuncExN03DataoDictRings::sizep2memfunc) {}
    size_t sizep2memfunc() { return(sizeof(p)); }
  private:
    size_t (G__Sizep2memfuncExN03DataoDictRings::*p)();
};

size_t G__get_sizep2memfuncExN03DataoDictRings()
{
  G__Sizep2memfuncExN03DataoDictRings a;
  G__setsizep2memfunc((int)a.sizep2memfunc());
  return((size_t)a.sizep2memfunc());
}


/*********************************************************
* virtual base class offset calculation interface
*********************************************************/

   /* Setting up class inheritance */

/*********************************************************
* Inheritance information setup/
*********************************************************/
extern "C" void G__cpp_setup_inheritanceExN03DataoDictRings() {

   /* Setting up class inheritance */
   if(0==G__getnumbaseclass(G__get_linked_tagnum(&G__ExN03DataoDictRingsLN_ExN03DataoRings))) {
     ExN03DataoRings *G__Lderived;
     G__Lderived=(ExN03DataoRings*)0x1000;
     {
       TObject *G__Lpbase=(TObject*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__ExN03DataoDictRingsLN_ExN03DataoRings),G__get_linked_tagnum(&G__ExN03DataoDictRingsLN_TObject),(long)G__Lpbase-(long)G__Lderived,1,1);
     }
   }
}

/*********************************************************
* typedef information setup/
*********************************************************/
extern "C" void G__cpp_setup_typetableExN03DataoDictRings() {

   /* Setting up typedef entry */
   G__search_typename2("Version_t",115,-1,0,-1);
   G__setnewtype(-1,"Class version identifier (short)",0);
   G__search_typename2("vector<ROOT::TSchemaHelper>",117,G__get_linked_tagnum(&G__ExN03DataoDictRingsLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__ExN03DataoDictRingsLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__ExN03DataoDictRingsLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__ExN03DataoDictRingsLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__ExN03DataoDictRingsLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TVirtualArray*>",117,G__get_linked_tagnum(&G__ExN03DataoDictRingsLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__ExN03DataoDictRingsLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__ExN03DataoDictRingsLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__ExN03DataoDictRingsLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__ExN03DataoDictRingsLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<int>",117,G__get_linked_tagnum(&G__ExN03DataoDictRingsLN_vectorlEintcOallocatorlEintgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__ExN03DataoDictRingsLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__ExN03DataoDictRingsLN_vectorlEintcOallocatorlEintgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__ExN03DataoDictRingsLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__ExN03DataoDictRingsLN_vectorlEintcOallocatorlEintgRsPgR));
   G__setnewtype(-1,NULL,0);
}

/*********************************************************
* Data Member information setup/
*********************************************************/

   /* Setting up class,struct,union tag member variable */

   /* ExN03DataoRings */
static void G__setup_memvarExN03DataoRings(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__ExN03DataoDictRingsLN_ExN03DataoRings));
   { ExN03DataoRings *p; p=(ExN03DataoRings*)0x1000; if (p) { }
   G__memvar_setup((void*)((long)(&p->datai)-(long)(p)),117,0,0,G__get_linked_tagnum(&G__ExN03DataoDictRingsLN_ExN03Datai),-1,-1,1,"datai=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->x_pad)-(long)(p)),117,0,0,G__get_linked_tagnum(&G__ExN03DataoDictRingsLN_vectorlEdoublecOallocatorlEdoublegRsPgR),G__defined_typename("vector<double>"),-1,1,"x_pad=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->y_pad)-(long)(p)),117,0,0,G__get_linked_tagnum(&G__ExN03DataoDictRingsLN_vectorlEdoublecOallocatorlEdoublegRsPgR),G__defined_typename("vector<double>"),-1,1,"y_pad=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->t_pad)-(long)(p)),117,0,0,G__get_linked_tagnum(&G__ExN03DataoDictRingsLN_vectorlEdoublecOallocatorlEdoublegRsPgR),G__defined_typename("vector<double>"),-1,1,"t_pad=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->dt)-(long)(p)),117,0,0,G__get_linked_tagnum(&G__ExN03DataoDictRingsLN_vectorlEdoublecOallocatorlEdoublegRsPgR),G__defined_typename("vector<double>"),-1,1,"dt=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->q_pad)-(long)(p)),117,0,0,G__get_linked_tagnum(&G__ExN03DataoDictRingsLN_vectorlEdoublecOallocatorlEdoublegRsPgR),G__defined_typename("vector<double>"),-1,1,"q_pad=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->Et_pad)-(long)(p)),100,0,0,-1,-1,-1,1,"Et_pad=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->nb_pads)-(long)(p)),105,0,0,-1,-1,-1,1,"nb_pads=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->NRings)-(long)(p)),105,0,0,-1,-1,-1,1,"NRings=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->NSegments)-(long)(p)),105,0,0,-1,-1,-1,1,"NSegments=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->sigL)-(long)(p)),100,0,0,-1,-1,-1,1,"sigL=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->sigT)-(long)(p)),100,0,0,-1,-1,-1,1,"sigT=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->driftV)-(long)(p)),100,0,0,-1,-1,-1,1,"driftV=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->Ionis)-(long)(p)),100,0,0,-1,-1,-1,1,"Ionis=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->TimeBinSize)-(long)(p)),100,0,0,-1,-1,-1,1,"TimeBinSize=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->ShapingTime)-(long)(p)),100,0,0,-1,-1,-1,1,"ShapingTime=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->Threshold)-(long)(p)),100,0,0,-1,-1,-1,1,"Threshold=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->Gain)-(long)(p)),100,0,0,-1,-1,-1,1,"Gain=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->NoiseRMS)-(long)(p)),100,0,0,-1,-1,-1,1,"NoiseRMS=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->Theta)-(long)(p)),100,0,0,-1,-1,-1,1,"Theta=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->FirstRing)-(long)(p)),100,0,0,-1,-1,-1,1,"FirstRing=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->LastRing)-(long)(p)),100,0,0,-1,-1,-1,1,"LastRing=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__ExN03DataoDictRingsLN_TClass),-1,-2,4,"fgIsA=",0,(char*)NULL);
   }
   G__tag_memvar_reset();
}

extern "C" void G__cpp_setup_memvarExN03DataoDictRings() {
}
/***********************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
***********************************************************/

/*********************************************************
* Member function information setup for each class
*********************************************************/
static void G__setup_memfuncExN03DataoRings(void) {
   /* ExN03DataoRings */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__ExN03DataoDictRingsLN_ExN03DataoRings));
   G__memfunc_setup("ExN03DataoRings",1370,G__ExN03DataoDictRings_189_0_1, 105, G__get_linked_tagnum(&G__ExN03DataoDictRingsLN_ExN03DataoRings), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("ClearEvent",1001,G__ExN03DataoDictRings_189_0_2, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("ReadConfigurationFile",2132,G__ExN03DataoDictRings_189_0_3, 121, -1, -1, 0, 1, 1, 1, 0, "u 'string' - 0 - -", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Class",502,G__ExN03DataoDictRings_189_0_4, 85, G__get_linked_tagnum(&G__ExN03DataoDictRingsLN_TClass), -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (TClass* (*)())(&ExN03DataoRings::Class) ), 0);
   G__memfunc_setup("Class_Name",982,G__ExN03DataoDictRings_189_0_5, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&ExN03DataoRings::Class_Name) ), 0);
   G__memfunc_setup("Class_Version",1339,G__ExN03DataoDictRings_189_0_6, 115, -1, G__defined_typename("Version_t"), 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (Version_t (*)())(&ExN03DataoRings::Class_Version) ), 0);
   G__memfunc_setup("Dictionary",1046,G__ExN03DataoDictRings_189_0_7, 121, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (void (*)())(&ExN03DataoRings::Dictionary) ), 0);
   G__memfunc_setup("IsA",253,(G__InterfaceMethod) NULL,85, G__get_linked_tagnum(&G__ExN03DataoDictRingsLN_TClass), -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("ShowMembers",1132,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TMemberInspector' - 1 - -", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Streamer",835,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - -", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("StreamerNVirtual",1656,G__ExN03DataoDictRings_189_0_11, 121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - ClassDef_StreamerNVirtual_b", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DeclFileName",1145,G__ExN03DataoDictRings_189_0_12, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&ExN03DataoRings::DeclFileName) ), 0);
   G__memfunc_setup("ImplFileLine",1178,G__ExN03DataoDictRings_189_0_13, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&ExN03DataoRings::ImplFileLine) ), 0);
   G__memfunc_setup("ImplFileName",1171,G__ExN03DataoDictRings_189_0_14, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&ExN03DataoRings::ImplFileName) ), 0);
   G__memfunc_setup("DeclFileLine",1152,G__ExN03DataoDictRings_189_0_15, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&ExN03DataoRings::DeclFileLine) ), 0);
   // automatic copy constructor
   G__memfunc_setup("ExN03DataoRings", 1370, G__ExN03DataoDictRings_189_0_16, (int) ('i'), G__get_linked_tagnum(&G__ExN03DataoDictRingsLN_ExN03DataoRings), -1, 0, 1, 1, 1, 0, "u 'ExN03DataoRings' - 11 - -", (char*) NULL, (void*) NULL, 0);
   // automatic destructor
   G__memfunc_setup("~ExN03DataoRings", 1496, G__ExN03DataoDictRings_189_0_17, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 1);
   // automatic assignment operator
   G__memfunc_setup("operator=", 937, G__ExN03DataoDictRings_189_0_18, (int) ('u'), G__get_linked_tagnum(&G__ExN03DataoDictRingsLN_ExN03DataoRings), -1, 1, 1, 1, 1, 0, "u 'ExN03DataoRings' - 11 - -", (char*) NULL, (void*) NULL, 0);
   G__tag_memfunc_reset();
}


/*********************************************************
* Member function information setup
*********************************************************/
extern "C" void G__cpp_setup_memfuncExN03DataoDictRings() {
}

/*********************************************************
* Global variable information setup for each class
*********************************************************/
static void G__cpp_setup_global0() {

   /* Setting up global variables */
   G__resetplocal();

}

static void G__cpp_setup_global1() {
}

static void G__cpp_setup_global2() {

   G__resetglobalenv();
}
extern "C" void G__cpp_setup_globalExN03DataoDictRings() {
  G__cpp_setup_global0();
  G__cpp_setup_global1();
  G__cpp_setup_global2();
}

/*********************************************************
* Global function information setup for each class
*********************************************************/
static void G__cpp_setup_func0() {
   G__lastifuncposition();

}

static void G__cpp_setup_func1() {
}

static void G__cpp_setup_func2() {
}

static void G__cpp_setup_func3() {
}

static void G__cpp_setup_func4() {
}

static void G__cpp_setup_func5() {
}

static void G__cpp_setup_func6() {
}

static void G__cpp_setup_func7() {
}

static void G__cpp_setup_func8() {
}

static void G__cpp_setup_func9() {
}

static void G__cpp_setup_func10() {
}

static void G__cpp_setup_func11() {
}

static void G__cpp_setup_func12() {
}

static void G__cpp_setup_func13() {
}

static void G__cpp_setup_func14() {

   G__resetifuncposition();
}

extern "C" void G__cpp_setup_funcExN03DataoDictRings() {
  G__cpp_setup_func0();
  G__cpp_setup_func1();
  G__cpp_setup_func2();
  G__cpp_setup_func3();
  G__cpp_setup_func4();
  G__cpp_setup_func5();
  G__cpp_setup_func6();
  G__cpp_setup_func7();
  G__cpp_setup_func8();
  G__cpp_setup_func9();
  G__cpp_setup_func10();
  G__cpp_setup_func11();
  G__cpp_setup_func12();
  G__cpp_setup_func13();
  G__cpp_setup_func14();
}

/*********************************************************
* Class,struct,union,enum tag information setup
*********************************************************/
/* Setup class/struct taginfo */
G__linked_taginfo G__ExN03DataoDictRingsLN_TClass = { "TClass" , 99 , -1 };
G__linked_taginfo G__ExN03DataoDictRingsLN_TBuffer = { "TBuffer" , 99 , -1 };
G__linked_taginfo G__ExN03DataoDictRingsLN_TMemberInspector = { "TMemberInspector" , 99 , -1 };
G__linked_taginfo G__ExN03DataoDictRingsLN_TObject = { "TObject" , 99 , -1 };
G__linked_taginfo G__ExN03DataoDictRingsLN_vectorlEdoublecOallocatorlEdoublegRsPgR = { "vector<double,allocator<double> >" , 99 , -1 };
G__linked_taginfo G__ExN03DataoDictRingsLN_string = { "string" , 99 , -1 };
G__linked_taginfo G__ExN03DataoDictRingsLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR = { "vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >" , 99 , -1 };
G__linked_taginfo G__ExN03DataoDictRingsLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR = { "reverse_iterator<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::iterator>" , 99 , -1 };
G__linked_taginfo G__ExN03DataoDictRingsLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR = { "vector<TVirtualArray*,allocator<TVirtualArray*> >" , 99 , -1 };
G__linked_taginfo G__ExN03DataoDictRingsLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TVirtualArray*,allocator<TVirtualArray*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__ExN03DataoDictRingsLN_ExN03Datai = { "ExN03Datai" , 99 , -1 };
G__linked_taginfo G__ExN03DataoDictRingsLN_vectorlEintcOallocatorlEintgRsPgR = { "vector<int,allocator<int> >" , 99 , -1 };
G__linked_taginfo G__ExN03DataoDictRingsLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<int,allocator<int> >::iterator>" , 99 , -1 };
G__linked_taginfo G__ExN03DataoDictRingsLN_ExN03DataoRings = { "ExN03DataoRings" , 99 , -1 };

/* Reset class/struct taginfo */
extern "C" void G__cpp_reset_tagtableExN03DataoDictRings() {
  G__ExN03DataoDictRingsLN_TClass.tagnum = -1 ;
  G__ExN03DataoDictRingsLN_TBuffer.tagnum = -1 ;
  G__ExN03DataoDictRingsLN_TMemberInspector.tagnum = -1 ;
  G__ExN03DataoDictRingsLN_TObject.tagnum = -1 ;
  G__ExN03DataoDictRingsLN_vectorlEdoublecOallocatorlEdoublegRsPgR.tagnum = -1 ;
  G__ExN03DataoDictRingsLN_string.tagnum = -1 ;
  G__ExN03DataoDictRingsLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR.tagnum = -1 ;
  G__ExN03DataoDictRingsLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__ExN03DataoDictRingsLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR.tagnum = -1 ;
  G__ExN03DataoDictRingsLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__ExN03DataoDictRingsLN_ExN03Datai.tagnum = -1 ;
  G__ExN03DataoDictRingsLN_vectorlEintcOallocatorlEintgRsPgR.tagnum = -1 ;
  G__ExN03DataoDictRingsLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__ExN03DataoDictRingsLN_ExN03DataoRings.tagnum = -1 ;
}


extern "C" void G__cpp_setup_tagtableExN03DataoDictRings() {

   /* Setting up class,struct,union tag entry */
   G__get_linked_tagnum_fwd(&G__ExN03DataoDictRingsLN_TClass);
   G__get_linked_tagnum_fwd(&G__ExN03DataoDictRingsLN_TBuffer);
   G__get_linked_tagnum_fwd(&G__ExN03DataoDictRingsLN_TMemberInspector);
   G__get_linked_tagnum_fwd(&G__ExN03DataoDictRingsLN_TObject);
   G__get_linked_tagnum_fwd(&G__ExN03DataoDictRingsLN_vectorlEdoublecOallocatorlEdoublegRsPgR);
   G__get_linked_tagnum_fwd(&G__ExN03DataoDictRingsLN_string);
   G__get_linked_tagnum_fwd(&G__ExN03DataoDictRingsLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR);
   G__get_linked_tagnum_fwd(&G__ExN03DataoDictRingsLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__ExN03DataoDictRingsLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR);
   G__get_linked_tagnum_fwd(&G__ExN03DataoDictRingsLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__ExN03DataoDictRingsLN_ExN03Datai);
   G__get_linked_tagnum_fwd(&G__ExN03DataoDictRingsLN_vectorlEintcOallocatorlEintgRsPgR);
   G__get_linked_tagnum_fwd(&G__ExN03DataoDictRingsLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR);
   G__tagtable_setup(G__get_linked_tagnum_fwd(&G__ExN03DataoDictRingsLN_ExN03DataoRings),sizeof(ExN03DataoRings),-1,29952,(char*)NULL,G__setup_memvarExN03DataoRings,G__setup_memfuncExN03DataoRings);
}
extern "C" void G__cpp_setupExN03DataoDictRings(void) {
  G__check_setup_version(30051515,"G__cpp_setupExN03DataoDictRings()");
  G__set_cpp_environmentExN03DataoDictRings();
  G__cpp_setup_tagtableExN03DataoDictRings();

  G__cpp_setup_inheritanceExN03DataoDictRings();

  G__cpp_setup_typetableExN03DataoDictRings();

  G__cpp_setup_memvarExN03DataoDictRings();

  G__cpp_setup_memfuncExN03DataoDictRings();
  G__cpp_setup_globalExN03DataoDictRings();
  G__cpp_setup_funcExN03DataoDictRings();

   if(0==G__getsizep2memfunc()) G__get_sizep2memfuncExN03DataoDictRings();
  return;
}
class G__cpp_setup_initExN03DataoDictRings {
  public:
    G__cpp_setup_initExN03DataoDictRings() { G__add_setup_func("ExN03DataoDictRings",(G__incsetup)(&G__cpp_setupExN03DataoDictRings)); G__call_setup_funcs(); }
   ~G__cpp_setup_initExN03DataoDictRings() { G__remove_setup_func("ExN03DataoDictRings"); }
};
G__cpp_setup_initExN03DataoDictRings G__cpp_setup_initializerExN03DataoDictRings;

