/********************************************************************
* ExN03SetupDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error ExN03SetupDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableExN03SetupDict();
extern void G__cpp_setup_inheritanceExN03SetupDict();
extern void G__cpp_setup_typetableExN03SetupDict();
extern void G__cpp_setup_memvarExN03SetupDict();
extern void G__cpp_setup_globalExN03SetupDict();
extern void G__cpp_setup_memfuncExN03SetupDict();
extern void G__cpp_setup_funcExN03SetupDict();
extern void G__set_cpp_environmentExN03SetupDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "ExN03Setup.hh"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__ExN03SetupDictLN_TClass;
extern G__linked_taginfo G__ExN03SetupDictLN_TBuffer;
extern G__linked_taginfo G__ExN03SetupDictLN_TMemberInspector;
extern G__linked_taginfo G__ExN03SetupDictLN_TObject;
extern G__linked_taginfo G__ExN03SetupDictLN_string;
extern G__linked_taginfo G__ExN03SetupDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__ExN03SetupDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__ExN03SetupDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__ExN03SetupDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__ExN03SetupDictLN_ExN03Setup;

/* STUB derived class for protected member access */
